on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write
  
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download data contract
        run: curl -o datacontract.yaml https://datacontract.com/examples/orders-latest/datacontract.yaml
      - name: Data Contract Tests
        uses: datacontract/datacontract-action@main
        # with:
          # location: https://datacontract.com/examples/orders-latest/datacontract.yaml
          # server: all
          
      - name: Echo
        if: always()
        run: cat TEST-datacontract.xml

      - name: Data Contract Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Data Contract Test Results
          path: ./TEST-datacontract.xml
          reporter: java-junit
          fail-on-error: 'false'

