on:
  pull_request:
  push:
  workflow_dispatch:
    
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 

      - name: Data Contract Test Results (EnricoMi/publish-unit-test-result-action)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()  
        with:
          files: |
            ./*.xml
            
      - name: Data Contract Test Results (dorny/test-reporter)
        uses: dorny/test-reporter@v1
        if: success() || failure()  
        with:
          name: Data Contract Test Results (dorny/test-reporter)
          path: ./TEST-datacontract.xml                  # Path to test results
          reporter: java-junit              # Format of test results
