on:
  push:
  workflow_dispatch:
    
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: datacontract/cli:latest
      options: --user root
    steps:
      - name: Run Tests
        run: datacontract test https://datacontract.com/examples/orders-latest/datacontract.yaml

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()  
        with:
          name: Data Contract Test Results
          path: ./TEST-datacontract.xml                  # Path to test results
          reporter: java-junit              # Format of test results
      
