on:
  push:
  workflow_dispatch:
    
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run datacontract test in Docker
        uses: addnab/docker-run-action@v3
        with:
            image: datacontract/cli:snapshot-latest
            options: -v ${{ github.workspace }}:/workspace
            run: |
              datacontract test \
              --output-format junit \
              --output /workspace/TEST-datacontract.xml \
              https://datacontract.com/examples/orders-latest/datacontract.yaml 
      - name: Echo
        if: ${{ always() }}
        run: cat ./TEST-datacontract.xml

      - name: Data Contract Test Results (dorny/test-reporter)
        uses: dorny/test-reporter@v1
        if: success() || failure()  
        with:
          name: Data Contract Test Results (dorny/test-reporter)
          path: ./TEST-datacontract.xml                  # Path to test results
          reporter: java-junit              # Format of test results
      
