on:
  push:
  workflow_dispatch:
    
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run datacontract test in Docker
        uses: addnab/docker-run-action@v3
        with:
            image: datacontract/cli:snapshot-latest
            options: -v ${{ github.workspace }}:/app/
            run: |
              datacontract test \
              --output-format junit \
              --output /app/TEST-datacontract.xml \
              https://datacontract.com/examples/orders-latest/datacontract.yaml 
      - name: Echo
        run: |
          cat ./TEST-datacontract.xml
              
